name: edu_vantage_app
description: Modern Learning Platform (Dark Slate Design)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase Core & Crashlytics
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.6
  
  # UI Components & Icons matching React design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  # تم تصحيح الإصدار هنا ليطابق الموجود في Pub.dev
  lucide_icons: ^0.257.0 
  cached_network_image: ^3.3.1
  
  # Security (مهم جداً لكود الحماية في main.dart)
  flutter_windowmanager_plus: ^1.0.1

  # Networking
  dio: ^5.4.0
  
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
