name: edu_vantage_app
description: Modern Learning Platform (Dark Slate Design)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core & Crashlytics
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  
  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  get_it: ^9.2.0
  
  # UI Components & Icons
  google_fonts: ^7.0.2
  flutter_svg: ^2.2.3
  url_launcher: ^6.3.2
  lucide_icons: ^0.257.0 
  cached_network_image: ^3.4.1
  percent_indicator: ^4.2.5 # شريط التقدم للتحميل
  device_info_plus: ^12.3.0
  android_id: ^0.5.1
  wakelock_plus: ^1.4.0        # لإبقاء الشاشة تعمل
  syncfusion_flutter_pdfviewer: ^32.1.23
  syncfusion_flutter_pdf: ^32.1.23
  
  
  # ✅ التعديل 1: استخدام نسخة GitHub للحصول على دوال الاستماع (addListener)
  screen_protector:
    git:
      url: https://github.com/prongbang/screen_protector.git
      ref: master

  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7
  safe_device: ^1.1.4
  flutter_local_notifications: ^19.5.0
  flutter_background_service: ^5.1.0
  
  # ✅ التعديل 2: تحديث الإصدار لدعم منع تسجيل الصوت
  audio_session: ^0.2.2 
  

  # Security & Privacy
  flutter_windowmanager_plus: ^1.0.1 # منع تصوير الشاشة
  encrypt: ^5.0.3 # التشفير (AES)
  flutter_secure_storage: ^9.0.0

  # Networking
  dio: ^5.4.0
  
  # Storage & Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2 # الوصول لمسارات الملفات
  permission_handler: ^11.3.0 # إدارة الأذونات

  # File Handling & Uploads
  image_picker: ^1.0.7 # اختيار صور الإيصالات

  # Video Players
  video_player: ^2.8.2
  chewie: ^1.7.4 # مشغل فيديو متقدم
  youtube_player_flutter: ^9.0.0 # مشغل يوتيوب

  # PDF Viewer
  flutter_pdfview: ^1.3.2

  # Local Server (Offline Playback Proxy)
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # مكتبة توليد الأيقونات
  flutter_launcher_icons: ^0.13.1

# إعدادات الأيقونة
flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  # مسار الصور
  assets:
    - assets/images/
